### ISSUE TITLE
Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by cravay** [cadenasgmbh/vscode-glsllint#13]
An error occured when I tried to enable this plugin. I managed to fix it by running `npm install typescript` in `~/.vscode/extensions/cadenas.vscode-glsllint-0.0.9`.

<details><summary><b>VScode information</b></summary>
<p>

```
Version: 1.43.1 (system setup)
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:20.184Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

</p>
</details>

<details><summary><b>Log (Extension Host)</b></summary>
<p>

```
[2020-03-19 17:37:06.189] [exthost] [info] ExtensionService#_doActivateExtension CADENAS.vscode-glsllint {"startup":true,"extensionId":{"value":"CADENAS.vscode-glsllint","_lower":"cadenas.vscode-glsllint"},"activationEvent":"*"}
[2020-03-19 17:37:06.189] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Michael/.vscode/extensions/cadenas.vscode-glsllint-0.0.9/out/src/extension
[2020-03-19 17:37:06.249] [exthost] [error] Activating extension CADENAS.vscode-glsllint failed due to an error:
[2020-03-19 17:37:06.253] [exthost] [error] Error: Cannot find module 'typescript'
Require stack:
- c:\Users\Michael\.vscode\extensions\cadenas.vscode-glsllint-0.0.9\out\src\features\glsllintProvider.js
- c:\Users\Michael\.vscode\extensions\cadenas.vscode-glsllint-0.0.9\out\src\extension.js
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:849:718)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:628)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:815:969)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\Michael\.vscode\extensions\cadenas.vscode-glsllint-0.0.9\out\src\features\glsllintProvider.js:26:12)
	at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:849:718)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:628)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:815:969)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\Michael\.vscode\extensions\cadenas.vscode-glsllint-0.0.9\out\src\extension.js:6:28)
	at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:849:718)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:628)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:815:969)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:32:963)
	at d._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:820:773)
	at d._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:720:856)
	at d._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:719:841)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:717:796)
	at d._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:522:206)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:521:900
	at Array.map (<anonymous>)
	at d._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:521:888)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:521:993
```

</p>
</details>

**Comment by hsimpson** [comment]
Can confirm this bug, was introduced with #6 there I need tyscript to walk through the AST.
